version: "3.7"

services:
  kratos-migrate:
    image: oryd/kratos:v0.5.5-alpha.1-sqlite
    command: -c /etc/config/kratos/kratos.yml migrate sql -e --yes
    environment:
      - DSN=sqlite:///var/lib/sqlite/db.sqlite?_fk=true&mode=rwc
    networks:
      - intranet
    restart: on-failure
    volumes:
      - type: volume
        source: kratos-sqlite
        target: /var/lib/sqlite
        read_only: false
      - type: bind
        source: ./services/auth/kratos
        target: /etc/config/kratos

  web:
    image: "node:lts-slim"
    command: ["yarn", "start"]
    depends_on:
      - kratos
    environment:
      - PATH=/srv/node_modules/.bin:$PATH
      - PORT=4435
      - KRATOS_BROWSER_URL=http://127.0.0.1:4455/.ory/kratos/public
      - JWKS_URL=http://localhost:4456/.well-known/jwks.json
      - SECURITY_MODE=jwks
    networks:
      - intranet
    ports:
      - "4435:4435"
    restart: on-failure
    stdin_open: true
    user: "node:node"
    volumes:
      - "./web:/srv:delegated"
    working_dir: "/srv"

  kratos:
    image: oryd/kratos:v0.5.5-alpha.1-sqlite
    command: serve -c /etc/config/kratos/kratos.yml --dev
    depends_on:
      - kratos-migrate
    environment:
      - DSN=sqlite:///var/lib/sqlite/db.sqlite?_fk=true
      - LOG_LEVEL=trace
      - SERVE_PUBLIC_BASE_URL=http://127.0.0.1:4455/.ory/kratos/public/
    networks:
      - intranet
    ports:
      - "4433:4433" # public
      - "4434:4434" # admin
    restart: unless-stopped
    volumes:
      - type: volume
        source: kratos-sqlite
        target: /var/lib/sqlite
        read_only: false
      - type: bind
        source: ./services/auth/kratos
        target: /etc/config/kratos

  oathkeeper:
    image: oryd/oathkeeper:v0.38
    command: serve proxy -c "/etc/config/oathkeeper/oathkeeper.yml"
    depends_on:
      - kratos
    environment:
      - LOG_LEVEL=debug
    networks:
      - intranet
    ports:
      - 4455:4455
      - 4456:4456
    restart: on-failure
    volumes:
      - ./services/auth/oathkeeper:/etc/config/oathkeeper

  mailslurper:
    image: oryd/mailslurper:latest-smtps
    networks:
      - intranet
    ports:
      - "4436:4436"
      - "4437:4437"

networks:
  intranet:

volumes:
  kratos-sqlite:
