[tasks.tailwind-install]
cwd = "./tailwind"
command = "yarn"
args = ["install"]

[tasks.tailwind-development]
cwd = "./tailwind"
command = "yarn"
args = ["development"]
dependencies = ["tailwind-install"]

[tasks.tailwind-production]
cwd = "./tailwind"
command = "yarn"
args = ["production"]
dependencies = ["tailwind-install"]

[tasks.rocket-development]
command = "cargo"
args = ["build"]

[tasks.rocket-production]
command = "cargo"
args = ["build", "--release"]

[tasks.serve]
command = "cargo"
args = ["run"]
watch = { watch = ["Rocket.toml", ".env", "./src/", "./tailwind/"] }
dependencies = ["tailwind-development", "rocket-development"]

[tasks.deploy]
dependencies = ["tailwind-production", "rocket-production"]
