[tasks.css-install]
cwd = "./css"
command = "yarn"
args = ["install"]
workspace = false

[tasks.css-build]
cwd = "./css"
command = "yarn"
args = ["development"]
dependencies = ["css-install"]
workspace = false

[tasks.css-release]
cwd = "./css"
command = "yarn"
args = ["production"]
dependencies = ["css-install"]
workspace = false

[tasks.serve]
run_task = "serve"
dependencies = ["css-build"]

[tasks.deploy]
run_task = "serve"
dependencies = ["css-release"]

[tasks.sql]
command = "psql"
args = ["postgres://cbzehner:foobar@localhost:5432/launchpad"]
workspace = false
