version: "3.7"

services:
  postgres-database:
    image: postgres:13.2
    env_file:
      - ./services/data/postgres/env.local
    networks:
      - intranet
    ports:
      - "5432:5432"
    restart: on-failure
    volumes:
      - type: volume
        source: postgres-data
        target: /var/lib/postgres/data
        read_only: false
      - type: bind
        source: ./services/data/postgres/init-db.sql
        target: /docker-entrypoint-initdb.d/init.sql

  kratos-migrate:
    image: oryd/kratos:v0.5.5-alpha.1
    command: -c /etc/config/kratos/kratos.yml migrate sql -e --yes
    depends_on:
      - postgres-database
    env_file:
      - ./services/auth/kratos/env.local
    networks:
      - intranet
    restart: on-failure
    volumes:
      - type: bind
        source: ./services/auth/kratos
        target: /etc/config/kratos

  kratos:
    image: oryd/kratos:v0.5.5-alpha.1
    command: serve -c /etc/config/kratos/kratos.yml --dev
    depends_on:
      - kratos-migrate
    env_file:
      - ./services/auth/kratos/env.local
    networks:
      - intranet
    ports:
      - "4433:4433" # public
      - "4434:4434" # admin
    restart: unless-stopped
    volumes:
      - type: bind
        source: ./services/auth/kratos
        target: /etc/config/kratos

  oathkeeper:
    image: oryd/oathkeeper:v0.38
    command: serve proxy -c "/etc/config/oathkeeper/oathkeeper.yml"
    depends_on:
      - kratos
    env_file:
      - ./services/auth/oathkeeper/env.local
    networks:
      - intranet
    ports:
      - 4455:4455
      - 4456:4456
    restart: on-failure
    volumes:
      - type: bind
        source: ./services/auth/oathkeeper
        target: /etc/config/oathkeeper

  web:
    image: "node:lts-slim"
    command: ["yarn", "start"]
    depends_on:
      - kratos
    env_file:
      - ./web/env.local
    environment:
      - PATH=/srv/node_modules/.bin:$PATH
      - PORT=4435
    networks:
      - intranet
    ports:
      - "4435:4435"
    restart: on-failure
    stdin_open: true
    user: "node:node"
    volumes:
      - "./web:/srv:delegated"
    working_dir: "/srv"

  # TODO: Run in local development only.
  mailslurper:
    image: oryd/mailslurper:latest-smtps
    networks:
      - intranet
    ports:
      - "4436:4436"
      - "4437:4437"

networks:
  intranet:

volumes:
  postgres-data: