# Local Variables:
# mode: makefile
# End:
# vim: set ft=make :

# List available recipes
default:
  @just --list

build:
  mdbook build

start:
  mdbook serve --open

run:
  mdbook serve

test:
  mdbook test

watch:
  mdbook watch
