version: "3.7"

services:
  postgres-database:
    environment:
      - POSTGRES_PASSWORD=POSTGRES_USER_PASSWORD
    volumes:
      # Make this volume permanent (How?)
      - type: bind
        source: /launchpad/postgres-data
        target: /var/lib/postgresql/data
      - type: bind
        source: /launchpad/services/data/postgres/init-db.sql
        target: /docker-entrypoint-initdb.d/init.sql

  kratos-migrate:
    environment:
      - DSN=postgres://kratos:${KRATOS_POSTGRES_PASSWORD}@postgres-database:5432/kratos?sslmode=disable&max_conns=20&max_idle_conns=4
      - LOG_LEVEL=info
    volumes:
      - type: bind
        source: /launchpad/services/auth/kratos
        target: /etc/config/kratos

  kratos:
    command: serve -c /etc/config/kratos/kratos.yml
    environment:
      - WEBSITE_URL
      - DSN=postgres://kratos:${KRATOS_POSTGRES_PASSWORD}@postgres-database:5432/kratos?sslmode=disable&max_conns=20&max_idle_conns=4
      - LOG_LEVEL=info
      - SERVE_PUBLIC_BASE_URL=${WEBSITE_URL}/.ory/kratos/public/
    volumes:
      - type: bind
        source: /launchpad/services/auth/kratos
        target: /etc/config/kratos

  oathkeeper:
    environment:
      - LOG_LEVEL=info
    volumes:
      - type: bind
        source: /launchpad/services/auth/oathkeeper
        target: /etc/config/oathkeeper

  web:
    image: ghcr.io/cbzehner/launchpad/web:latest
    command: /bin/bash -c "envsubst < /etc/nginx/conf.d/site.template > /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'"
    environment:
      - WEBSITE_URL
      - KRATOS_BROWSER_URL=${WEBSITE_URL}/.ory/kratos/public
      - REACT_APP_KRATOS_BROWSER_URL=${KRATOS_BROWSER_URL}
      - PORT=4435
      - JWKS_URL=WEB_JWKS_URL
      - SECURITY_MODE=jwks

  api:
    image: ghcr.io/cbzehner/launchpad/api:latest
    environment:
      - KRATOS_URL=http://kratos:4433
      - POSTGRES_URL=postgres://api:${API_POSTGRES_PASSWORD}@postgres-database:5432/api
      - ROCKET_ADDRESS=0.0.0.0
      - ROCKET_LOG_LEVEL=normal
      - ROCKET_PORT=4438
      - ROCKET_SECRET_KEY=IkdKUejNsfs1qluIVEaN/Wp1JbdIuP7uwRGC91m+fUs=