version: "3.7"

services:
  postgres-database:
    env_file:
      - ./services/data/postgres/env.local
    ports:
      - "5432:5432"
    volumes:
      - type: bind
        source: ./.data/postgres-data
        target: /var/lib/postgresql/data
      - type: bind
        source: ./services/data/postgres/init-db.sql
        target: /docker-entrypoint-initdb.d/init.sql

  kratos-migrate:
    env_file:
      - ./services/auth/kratos/local/env.local
    volumes:
      - type: bind
        source: ./services/auth/kratos/local
        target: /etc/config/kratos

  kratos:
    command: serve -c /etc/config/kratos/kratos.yml --dev
    env_file:
      - ./services/auth/kratos/local/env.local
    ports:
      - "4433:4433" # public
      - "4434:4434" # admin
    volumes:
      - type: bind
        source: ./services/auth/kratos/local
        target: /etc/config/kratos

  oathkeeper:
    env_file:
      - ./services/auth/oathkeeper/local/env.local
    volumes:
      - type: bind
        source: ./services/auth/oathkeeper/local
        target: /etc/config/oathkeeper

  reverse-proxy:
    build:
      context: ./infrastructure/reverse-proxy/
      dockerfile: Dockerfile
    volumes:
      - type: bind
        source: ./infrastructure/reverse-proxy/nginx/development.conf
        target: /etc/nginx/conf.d/default.conf

  web:
    image: ghcr.io/cbzehner/launchpad/web:latest
    build:
      context: ./services/web/
      dockerfile: Dockerfile.dev
    env_file:
      - ./services/web/env.local
    ports:
      - "4435:4435"

  api:
    image: ghcr.io/cbzehner/launchpad/api:latest
    build:
      context: ./services/api/
      dockerfile: Dockerfile.dev
    env_file:
      - ./services/api/env.local
    ports:
      - "4438:4438"

  mailslurper:
    image: oryd/mailslurper:latest-smtps
    ports:
      - "4436:4436"
      - "4437:4437"