version: "3.7"

services:
  postgres-database:
    environment:
      - POSTGRES_PASSWORD=POSTGRES_USER_PASSWORD
    volumes:
      - type: bind
        source: /launchpad/postgres-data
        target: /var/lib/postgresql/data
      - type: bind
        source: /launchpad/services/data/postgres/init-db.sql
        target: /docker-entrypoint-initdb.d/init.sql

  kratos-migrate:
    volumes:
      - type: bind
        source: /launchpad/services/auth/kratos
        target: /etc/config/kratos

  kratos:
    command: serve -c /etc/config/kratos/kratos.yml
    volumes:
      - type: bind
        source: /launchpad/services/auth/kratos
        target: /etc/config/kratos

  oathkeeper:
    volumes:
      - type: bind
        source: /launchpad/services/auth/oathkeeper
        target: /etc/config/oathkeeper

  web:
    image: "node:lts-slim"
    command: ["yarn", "start"]
    env_file:
      - ./services/web/env.local
    environment:
      - PATH=/srv/node_modules/.bin:$PATH
      - PORT=4435
    ports:
      - "4435:4435"
    stdin_open: true
    user: "node:node"
    volumes:
      - "./services/web:/srv:delegated"
    working_dir: "/srv"

  api:
    env_file:
      - ./services/api/env.local
    ports:
      - "4438:4438"

  mailslurper:
    image: oryd/mailslurper:latest-smtps
    ports:
      - "4436:4436"
      - "4437:4437"