[tasks.build]
command = "cargo"
args = ["build"]

[tasks.deploy]
dependencies = ["build-release"]

[tasks.start]
command = "cargo"
args = ["run"]
watch = { watch = [
        "./Rocket.toml",
        "./src/",
        "../.env",
        "../css/tailwind.css",
        "../css/tailwind.config.js",
    ] }
