FROM nginx:stable AS nginx
RUN apt update && apt install -y ca-certificates && update-ca-certificates

FROM node:lts-buster-slim AS builder
WORKDIR /app
COPY package.json yarn.lock ./
RUN yarn install --frozen-lockfile
COPY . .
RUN yarn build

FROM nginx AS runtime
# Remove default nginx index page
RUN rm -rf /usr/share/nginx/html/*
COPY ./nginx/nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=builder /app/build /usr/share/nginx/html
CMD [ "nginx", "-g", "daemon off;" ]