FROM node:lts-buster-slim AS builder
RUN apt update && \
    apt install -y ca-certificates && \
    update-ca-certificates
WORKDIR /app
COPY package.json yarn.lock ./
RUN yarn install --frozen-lockfile
COPY . .
ENTRYPOINT [ "yarn", "start" ]