FROM node:lts-buster-slim AS builder
WORKDIR /app
COPY package.json yarn.lock ./
RUN yarn install --frozen-lockfile
COPY . .
RUN yarn build

FROM caddy:2.3.0 AS runtime
RUN rm -rf /usr/share/caddy/*
COPY --from=builder /app/build /usr/share/caddy
CMD [ "caddy", "file-server", "--listen", ":4435"]