# Local Variables:
# mode: makefile
# End:
# vim: set ft=make :

# List available recipes
default:
  @just --list

initialize:
  yarn install --frozen-lockfile

build:
  yarn build

start:
  yarn start

run:
  yarn start

test:
  yarn test

watch:
  yarn start

verify:
  just _format _lint _compile

_format:
  yarn format --check

_lint:
  yarn lint

_compile:
  yarn tsc --pretty