FROM rust:slim AS rust
RUN apt update && apt -y upgrade\
    && apt install -y \
    # Required by diesel_migration.
    libpq-dev \
    ca-certificates \
    && update-ca-certificates

FROM rust AS planner
WORKDIR /plan
# We only pay the installation cost once,
# it will be cached from the second build onwards
# To ensure a reproducible build consider pinning
# the cargo-chef version with `--version X.X.X`
RUN cargo install cargo-chef
COPY . .
RUN cargo chef prepare  --recipe-path recipe.json

FROM rust AS cache-layer
WORKDIR /cache-dependencies
RUN cargo install cargo-chef
COPY --from=planner /plan/recipe.json recipe.json
RUN cargo chef cook --recipe-path recipe.json

FROM rust AS builder
WORKDIR /build
COPY . .
# Copy over the cached dependencies
COPY --from=cache-layer /cache-dependencies/target target
COPY --from=cache-layer /usr/local/cargo /usr/local/cargo
ENTRYPOINT [ "cargo", "run", "--bin", "api"]