# Local Variables:
# mode: makefile
# End:
# vim: set ft=make :

# List available recipes
default:
  @just --list

build:
  cargo build

start:
  cargo watch -x 'run --bin api'

run:
  cargo run --bin api

test:
  cargo test -- --test-threads=1

unit:
  cargo test --lib

integration:
  cargo test --test integration -- --test-threads=1

watch:
  cargo watch
