# Local Variables:
# mode: makefile
# End:
# vim: set ft=make :

# List available recipes
default:
  @just --list

build:
  cargo build

start:
  cargo watch -x run

run:
  cargo run

test:
  cargo test

watch:
  cargo watch
