name: API Database

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    paths:
      - .github/workflows/api-database.yaml
      - services/api/migrations/**

env:
  CARGO_TERM_COLOR: always
  DATABASE_URL: postgres://api:secret@localhost:5432/api_test

defaults:
  run:
    working-directory: services/api

jobs:
  reversible-migrations:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: api
          POSTGRES_DB: api_test
          POSTGRES_PASSWORD: secret
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v2

      - name: Install diesel-cli binary crate
        uses: actions-rs/install@v0.1
        with:
          crate: diesel_cli
          version: latest
          use-tool-cache: true

      - name: Run all migrations
        run: diesel migration run

      # TODO: Handle all Postgres migrations added by Pull Request, not just latest. 
      - name: Ensure latest migration is reversible
        run: diesel migration redo